# Use a Node.js base image for serving the Flutter app
FROM node:14-alpine as build

# Set the working directory
WORKDIR /app

# Copy the web build output to the /app directory
COPY build/web .

# Install a lightweight HTTP server to serve the Flutter web app
RUN npm install -g http-server

# Expose the port on which the app will run
EXPOSE 8080

# Start the HTTP server to serve the app
CMD ["http-server", "-p", "8080"]
