name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull_requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest  # Adjust if necessary based on runner OS compatibility

    steps:
      - uses: actions/checkout@v4

      # **Optional for manual Flutter installation within the workflow:**
      - name: Install Flutter (if not available on runner)
        # Replace with the appropriate installation steps for your chosen method

      # Update PATH environment variable if necessary (refer to installation method)

      - run: flutter pub get

      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LCFLUTTER_45D62 }}
          projectId: lcflutter-45D62
