name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest  # Or your preferred runner OS

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: google/setup-flutter@v2  # Or a similar action
        with:
          flutter-version: '3.22'  # Adjust if needed

      - run: flutter pub get

      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LCFLUTTER_45D62 }}
          projectId: lcflutter-45D62
